name: 'helios/actions-opsgenie'
description: 'Send an alert using OpsGenie API V2'
author: 'Helios Dev <dev@gethelios.dev>'

branding:
  icon: 'x'
  color: 'red'

inputs:
  alias:
    description: 'Unique identifier for this type of alert (used to de-duplicate alerts)'
    required: true
  priority:
    description: 'Alert priority level (one of the P1-P5 OpsGenie alert levels)'
    required: true
  message:
    description: 'Message to attach to the alert'
    required: true
  api_key:
    description: 'OpsGenie API Key'
    required: true
  team:
    description: 'OpsGenie Team tag'
    required: false
    default: ""
  tags:
    description: 'Optional tags to add the the alert'
    required: false
    default: ""
  description:
    description: 'Optional description to add the the alert'
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alias }}
    - ${{ inputs.message }}
    - ${{ inputs.priority }}
    - ${{ inputs.api_key }}
    - ${{ inputs.team }}
    - ${{ inputs.tags }}
    - ${{ inputs.description }}
